version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:3306"
    networks:
      - backend
    volumes:
      - ./backend/sql:/docker-entrypoint-initdb.d

  # frontend:
  #   build:
  #     context: ./frontend
  #   container_name: frontend_app
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - frontend

  api:
    build:
      context: ./backend
    container_name: fastapi_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - backend

networks:
  backend:
    driver: bridge
  # frontend:
  #   driver: bridge
